FROM php:7.3.6

ADD files/docker-php-pecl-install /usr/local/bin

RUN apt-get update && apt-get install -y unzip git libzip-dev zip libpng-dev zlib1g-dev libicu-dev g++ libxml2-dev libsqlite3-dev librabbitmq-dev

RUN docker-php-ext-install pdo_mysql zip gd exif intl xmlwriter pdo_sqlite

RUN docker-php-pecl-install amqp-1.9.4

RUN docker-php-pecl-install apfd-1.0.2

RUN docker-php-pecl-install redis

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer