FROM genisyx/php:php7

ADD files/php.ini /usr/local/etc/php/php.ini

RUN apt-get update && \
    apt-get install -y libzmq-dev pkg-config libssl-dev supervisor

RUN docker-php-pecl-install zmq-1.1.3 && \
    docker-php-pecl-install mongodb-1.2.8