FROM php:5-fpm

ADD files/docker-php-pecl-install /usr/local/bin
ADD files/php.ini /usr/local/etc/php/php.ini

RUN apt-get update && \
    apt-get install -y zlib1g-dev libicu-dev g++ zip unzip curl git

RUN docker-php-ext-configure intl && \
    docker-php-ext-install intl

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    php composer-setup.php --install-dir=/usr/bin --filename=composer && \
    php -r "unlink('composer-setup.php');"
