FROM genisyx/php:php7.2-apache

ADD files/docker-php-pecl-install /usr/local/bin
ADD files/xdebug.ini /usr/local/etc/php/conf.d/my-xdebug-php.ini

RUN version=$(php -r "echo PHP_MAJOR_VERSION.PHP_MINOR_VERSION;") \
    && curl -A "Docker" -o /tmp/blackfire-probe.tar.gz -D - -L -s https://blackfire.io/api/v1/releases/probe/php/linux/amd64/$version \
    && tar zxpf /tmp/blackfire-probe.tar.gz -C /tmp \
    && mv /tmp/blackfire-*.so $(php -r "echo ini_get('extension_dir');")/blackfire.so \
    && printf "extension=blackfire.so\nblackfire.agent_socket=tcp://blackfire:8707\n" > $PHP_INI_DIR/conf.d/blackfire.ini

RUN docker-php-pecl-install xdebug-2.6.1

ADD php/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
